### ISSUE TITLE
Defines must not be used instead of enums

### ISSUE THREAD

**Issue by KOLANICH** [libpwquality/libpwquality#6]
https://github.com/libpwquality/libpwquality/blob/master/src/pwquality.h#L17

**Comment by t8m** [comment]
Why?

**Comment by t8m** [comment]
And no, I will not change that as it would be an API change.

**Comment by nmav** [comment]
There is no much difference and in APIs both are usually used. As enums are part of the language usually they show up on debugger as text instead of numerically. On the other hand one cannot write conditional code with enums, i.e., `#ifdef THIS_IS_DEFINED`. So indeed that's can result to a nice discussion on which is better, but there is little point to change an existing API from one to the other.
